### PR TITLE
Negation in XRewrite

### PR DESCRIPTION
**Pull request by gzanitti**
Fix error in XRewrite when trying to process negations.

### CODE REVIEW

**Comment by gzanitti** [comment]
Reminder:
- Compromise solution that allows to solve negations by means of XRewriter avoiding to evaluate them (at the moment it fulfills the requirements of our examples).
- We should evaluate the case where the unification is done between two negations.

I will convert the PR into a draft until then.

**Comment by demianw** [comment]
@gzanitti can we add a test for the negation of an existential rule and the corresponding exception?

**Comment by gzanitti** [comment]
> @gzanitti can we add a test for the negation of an existential rule and the corresponding exception?

The test added in this PR, fulfills the necessary condition, it only remains to define how to treat it. If we throw an exception every time there is a negated existential, all the examples we are already working on will stop running. Even if the negation does not influence the result.

I believe that I should throw the exception only in the case where, given the removal of the negation in the atom, the term has a constraint to unify with. What do you think?

**Comment by demianw** [comment]
Can you give me a little code example?

**Comment by gzanitti** [comment]
@demianw the tests fail because NeuroSynth is not installed. Any ideas?

`ImportError: Neurosynth not installed in the system`

**Comment by demianw** [comment]
@gzanitti can we have the status of this? We need to merge this or it has been solved elsewhere?

**Comment by gzanitti** [comment]
> @gzanitti can we have the status of this? We need to merge this or it has been solved elsewhere?

Should be solved in another PR, but let me confirm.

**Pull request closed without merging**
